extends:
    - 'eslint:recommended'
    - 'plugin:@typescript-eslint/recommended'
parser: '@typescript-eslint/parser'
plugins:
    - '@typescript-eslint'
root: true
ignorePatterns:
    - '**/dist/**'
env:
    node: true

overrides:
    - files: ['**/__test__/**']
      rules:
          '@typescript-eslint/ban-ts-comment': [warn]
