name: Build and Release

on:
    push:
        tags: ['*@*']

env:
    NODE_VERSION: '16.x'

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v3
            - name: Use Node ${{ env.NODE_VERSION }}
              uses: actions/setup-node@v3
              with:
                  node-version: ${{ env.NODE_VERSION }}
                  registry-url: 'https://registry.npmjs.org'

            - run: npm ci
            - run: npm test
            - run: lerna exec npm publish
              env:
                NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

            - name: Upload artifact
              uses: actions/upload-artifact@v3
              with:
                  name: target
                  path: ${{ github.workspace }}/dist/**/*
            - name: Extract changelog content
              run: |
                  sed -n "/^## \[${{ steps.publish.outputs.tag }}]/,/^## /p" CHANGELOG.md | sed '1d;$d' > changelog_body.md
            - name: Release
              uses: softprops/action-gh-release@v1
              with:
                  body_path: changelog_body.md
                  draft: true
                  prerelease: false
                  files: |
                      README.md
                      CHANGELOG.md
                  fail_on_unmatched_files: true
              env:
                  GITHUB_TOKEN: ${{ secrets.TOKEN }}
